### ISSUE TITLE
System path incorrect

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/devstarter#1]
I thought I'd try switching one of my 4.0.0-beta3 apps over to the dev branch so I'd have something to test on with the latest changes. After firing this up based on the user docs (`composer create-project codeigniter4/devstarter -s dev`) I found that it wasn't working. First issue is that `$systemDirectory` is pointing at where it should be for the AppStarter (`vendor/codeigniter4/framework`) instead of for the VCS-defined repo (`vendor/codeigniter4/codeigniter4`). This appears to be a file that is synced with AppStarter so I'm not sure how to go about excluding it, but the actual change is minor.

EDIT: Should have specified, `$systemDirectory` in app/Config/Paths.php

**Comment by MGatner** [comment]
I believe this is still valid.

**Comment by jim-parry** [comment]
See comment for closed PR

**Comment by MGatner** [comment]
The issue is that both appstarter and devstarter are receiving the same **Config/Paths.php**, but the former uses the released framework as a dependency (`codeginiter4/framework`) and the latter uses the development repo directly (`codeigniter4/codeigniter4`). I suspect it will take some search-and-replace action in **admin/release-framework** but until it is implemented the devstarter install instructions in the User Guide will create a project that won't run:
`composer create-project codeigniter4/devstarter -s dev`

**Comment by jim-parry** [comment]
I have updated app/Config/Paths.php in the devstarter.
That repo isn't "released" the same way the framework and app starter are, but the way the directions are written up, a "composer update" should now fix the incorrect system path.

**Comment by MGatner** [comment]
Great! Thank you for addressing that.
